### ISSUE TITLE
First time usage of bank panel showed only default bank (not bags)

### ISSUE THREAD

**Issue by radhaz** [checkem/SUCC-bag#2] opened 2017-02-23 23:07 UTC
The first time I used the bank portion only my bank inventory was present. Once I clicked one of the actual bank bags it opened the panel with bank bags and stayed open every time I accessed the bank.

**Comment by checkem** [comment] 2017-02-25 07:46
Please check if the issue is resolved in https://github.com/checkem/SUCC-bag/commit/6b18bd582dfa84c4305ad1ea4be50bd268d5f97c

I don't really understand what do you mean. The bank bag items are meant to open in a separate panel like the bag **slots** of the player inventory.

**Comment by radhaz** [comment] 2017-02-25 16:40
To explain further:
Currently opening your bag(s) results in a single unified panel with all your inventory conveniently accessible.

When you open the bank inventory you get the initial bank panel, and then you have to conduct an extra action to access the panel with the remaining bank bags.

I think the behavior between the bank bags and your carrying inventory should be the same ie I click bank and it opens all the bags at once but if this is a "feature" the so be it.

**Comment by checkem** [comment] 2017-02-26 01:40
That, actually, makes lots of sense. And it would be easier to make bank the same as the inventory. This I will have to reconsider, then again I would like to have the current bank layout and to layout inventory like the bank as an option. I have to set the milestone 'settings' or something.

**Comment by radhaz** [comment] 2017-03-09 16:34
Latest update resolves this issue entirely!

**Closed** 2017-03-09 16:35 UTC
